module Scrapedo
  VERSION: String
  def self.google: -> GoogleBuilder
end

class GoogleBuilder
  CONFIG_PATH: Pathname
  FILE_MAP: Hash[Symbol, String]

  @has_next: bool
  @data: Hash[Object, Object]
  @params_cache: Hash[Object, Object]
  @all_params: bool

  def initialize: (String) -> void

  def next?: () -> bool

  def search: (String) -> GoogleBuilder

  def device: -> GoogleBuilder

  def include_html: -> GoogleBuilder

  def hl: -> GoogleBuilder
  alias host_language hl

  def gl: -> GoogleBuilder
  alias geo_location gl

  def google_domain: -> GoogleBuilder
  alias domain google_domain

  def location: -> GoogleBuilder

  def uule: -> GoogleBuilder

  def lr: -> GoogleBuilder
  alias language_restrict lr

  def cr: -> GoogleBuilder
  alias country_restrict cr

  def safe_search: -> GoogleBuilder

  def enable_nfpr: -> GoogleBuilder

  def disable_filter: -> GoogleBuilder

  def start: (Integer) -> Hash[String, String]

  def next: -> Hash[String, String]

  def params: -> GoogleBuilder

  def scrapedo_url: -> URI::Generic

  private

  def load_yaml: (String) -> Hash[Object, String]

  def find_config_source: (Symbol | String) -> [Symbol, Hash[Symbol, Object]]?

  def blank?: (Object) -> bool

end
